module.exports = [
  {
    Symbol: 'TSLA',
    AssetType: 'Common Stock',
    Name: 'Tesla, Inc',
    Description:
      'Tesla, Inc. designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems in the United States, China, Netherlands, Norway, and internationally. The company operates in two segments, Automotive; and Energy Generation and Storage. The Automotive segment offers sedans and sport utility vehicles. It also provides electric powertrain components and systems; and services for electric vehicles through its company-owned service locations, and Tesla mobile service technicians, as well as sells used vehicles. This segment markets and sells its products through a network of company-owned stores and galleries, as well as through its own Website. The Energy Generation and Storage segment offers energy storage products, such as rechargeable lithium-ion battery systems for use in homes, industrial, commercial facilities, and utility grids; and designs, manufactures, installs, maintains, leases, and sells solar energy generation and energy storage products to residential and commercial customers. It also provides vehicle insurance services, as well as renewable energy. The company was formerly known as Tesla Motors, Inc. and changed its name to Tesla, Inc. in February 2017. Tesla, Inc. was founded in 2003 and is headquartered in Palo Alto, California.',
    Exchange: 'NASDAQ',
    Currency: 'USD',
    Country: 'USA',
    Sector: 'Consumer Cyclical',
    Industry: 'Auto Manufacturers',
    MarketCapitalization: '823094083584',
    EBITDA: '4019000064',
    PERatio: '1660.2932',
    PEGRatio: '1.6997',
    BookValue: '16.91',
    EPS: '0.523',
    EVToRevenue: '28.5052',
    EVToEBITDA: '205.8336',
    Beta: '2.1907',
  },
  {
    Symbol: 'IBM',
    AssetType: 'Common Stock',
    Name: 'International Business Machines Corporation',
    Description:
      "International Business Machines Corporation provides integrated solutions and services worldwide. Its Cloud & Cognitive Software segment offers software for vertical and domain-specific solutions in health, financial services, and Internet of Things (IoT), weather, and security software and services application areas; and customer information control system and storage, and analytics and integration software solutions to support client mission critical on-premise workloads in banking, airline, and retail industries. It also offers middleware and data platform software, including Red Hat that enables the operation of clients' hybrid multi-cloud environments; and Cloud Paks, WebSphere distributed, and analytics platform software, such as DB2 distributed, information integration, and enterprise content management, as well as IoT, Blockchain and AI/Watson platforms. The company's Global Business Services segment offers business consulting services; system integration, application management, maintenance, and support services for packaged software; finance, procurement, talent and engagement, and industry-specific business process outsourcing services; and IT infrastructure and platform services. Its Global Technology Services segment provides project, managed, outsourcing, and cloud-delivered services for enterprise IT infrastructure environments; and IT infrastructure support services. The company's Systems segment offers servers for businesses, cloud service providers, and scientific computing organizations; data storage products and solutions; and z/OS, an enterprise operating system, as well as Linux. Its Global Financing segment provides lease, installment payment, loan financing, short-term working capital financing, and remanufacturing and remarketing services. The company was formerly known as Computing-Tabulating-Recording Co. The company was founded in 1911 and is headquartered in Armonk, New York.",
    Exchange: 'NYSE',
    Currency: 'USD',
    Country: 'USA',
    Sector: 'Technology',
    Industry: 'Information Technology Services',
    MarketCapitalization: '105425412096',
    EBITDA: '13509000192',
    PERatio: '18.9942',
    PEGRatio: '8.8206',
    BookValue: '23.075',
    EPS: '6.229',
    EVToRevenue: '2.1508',
    EVToEBITDA: '12.5472',
    Beta: '1.2416',
  },
  {
    Symbol: 'AAPL',
    AssetType: 'Common Stock',
    Name: 'Apple Inc',
    Description:
      'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. It also sells various related services. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, HomePod, iPod touch, and other Apple-branded and third-party accessories. It also provides AppleCare support services; cloud services store services; and operates various platforms, including the App Store, that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts. In addition, the company offers various services, such as Apple Arcade, a game subscription service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV+, which offers exclusive original content; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It sells and delivers third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. was founded in 1977 and is headquartered in Cupertino, California.',
    Exchange: 'NASDAQ',
    Currency: 'USD',
    Country: 'USA',
    Sector: 'Technology',
    Industry: 'Consumer Electronics',
    MarketCapitalization: '2386553470976',
    EBITDA: '77343997952',
    PERatio: '43.25',
    PEGRatio: '3.4629',
    BookValue: '3.849',
    EPS: '3.28',
    EVToRevenue: '8.601',
    EVToEBITDA: '29.1422',
    Beta: '1.2836',
  },
];

// module.exports = [
//   {
//     Symbol: 'TSLA',
//     AssetType: 'Common Stock',
//     Name: 'Tesla, Inc',
//     Description:
//       'Tesla, Inc. designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems in the United States, China, Netherlands, Norway, and internationally. The company operates in two segments, Automotive; and Energy Generation and Storage. The Automotive segment offers sedans and sport utility vehicles. It also provides electric powertrain components and systems; and services for electric vehicles through its company-owned service locations, and Tesla mobile service technicians, as well as sells used vehicles. This segment markets and sells its products through a network of company-owned stores and galleries, as well as through its own Website. The Energy Generation and Storage segment offers energy storage products, such as rechargeable lithium-ion battery systems for use in homes, industrial, commercial facilities, and utility grids; and designs, manufactures, installs, maintains, leases, and sells solar energy generation and energy storage products to residential and commercial customers. It also provides vehicle insurance services, as well as renewable energy. The company was formerly known as Tesla Motors, Inc. and changed its name to Tesla, Inc. in February 2017. Tesla, Inc. was founded in 2003 and is headquartered in Palo Alto, California.',
//     Exchange: 'NASDAQ',
//     Currency: 'USD',
//     Country: 'USA',
//     Sector: 'Consumer Cyclical',
//     Industry: 'Auto Manufacturers',
//     Address: '3500 Deer Creek Road, Palo Alto, CA, United States, 94304',
//     FullTimeEmployees: '48016',
//     FiscalYearEnd: 'December',
//     LatestQuarter: '2020-09-30',
//     MarketCapitalization: '823094083584',
//     EBITDA: '4019000064',
//     PERatio: '1660.2932',
//     PEGRatio: '1.6997',
//     BookValue: '16.91',
//     DividendPerShare: 'None',
//     DividendYield: '0',
//     EPS: '0.523',
//     RevenuePerShareTTM: '30.668',
//     ProfitMargin: '0.0197',
//     OperatingMarginTTM: '0.0612',
//     ReturnOnAssetsTTM: '0.0274',
//     ReturnOnEquityTTM: '0.0559',
//     RevenueTTM: '28175998976',
//     GrossProfitTTM: '4069000000',
//     DilutedEPSTTM: '0.523',
//     QuarterlyEarningsGrowthYOY: '0.694',
//     QuarterlyRevenueGrowthYOY: '0.392',
//     AnalystTargetPrice: '544.07',
//     TrailingPE: '1660.2932',
//     ForwardPE: '208.3333',
//     PriceToSalesRatioTTM: '30.5816',
//     PriceToBookRatio: '50.0612',
//     EVToRevenue: '28.5052',
//     EVToEBITDA: '205.8336',
//     Beta: '2.1907',
//     '52WeekHigh': '884.49',
//     '52WeekLow': '70.102',
//     '50DayMovingAverage': '724.93',
//     '200DayMovingAverage': '479.0713',
//     SharesOutstanding: '947900992',
//     SharesFloat: '759562336',
//     SharesShort: '60620873',
//     SharesShortPriorMonth: '45227476',
//     ShortRatio: '1.11',
//     ShortPercentOutstanding: '0.06',
//     ShortPercentFloat: '0.0798',
//     PercentInsiders: '19.985',
//     PercentInstitutions: '42.529',
//     ForwardAnnualDividendRate: '0',
//     ForwardAnnualDividendYield: '0',
//     PayoutRatio: '0',
//     DividendDate: 'None',
//     ExDividendDate: 'None',
//     LastSplitFactor: '5:1',
//     LastSplitDate: '2020-08-31',
//   },
//   {
//     Symbol: 'IBM',
//     AssetType: 'Common Stock',
//     Name: 'International Business Machines Corporation',
//     Description:
//       "International Business Machines Corporation provides integrated solutions and services worldwide. Its Cloud & Cognitive Software segment offers software for vertical and domain-specific solutions in health, financial services, and Internet of Things (IoT), weather, and security software and services application areas; and customer information control system and storage, and analytics and integration software solutions to support client mission critical on-premise workloads in banking, airline, and retail industries. It also offers middleware and data platform software, including Red Hat that enables the operation of clients' hybrid multi-cloud environments; and Cloud Paks, WebSphere distributed, and analytics platform software, such as DB2 distributed, information integration, and enterprise content management, as well as IoT, Blockchain and AI/Watson platforms. The company's Global Business Services segment offers business consulting services; system integration, application management, maintenance, and support services for packaged software; finance, procurement, talent and engagement, and industry-specific business process outsourcing services; and IT infrastructure and platform services. Its Global Technology Services segment provides project, managed, outsourcing, and cloud-delivered services for enterprise IT infrastructure environments; and IT infrastructure support services. The company's Systems segment offers servers for businesses, cloud service providers, and scientific computing organizations; data storage products and solutions; and z/OS, an enterprise operating system, as well as Linux. Its Global Financing segment provides lease, installment payment, loan financing, short-term working capital financing, and remanufacturing and remarketing services. The company was formerly known as Computing-Tabulating-Recording Co. The company was founded in 1911 and is headquartered in Armonk, New York.",
//     Exchange: 'NYSE',
//     Currency: 'USD',
//     Country: 'USA',
//     Sector: 'Technology',
//     Industry: 'Information Technology Services',
//     Address: 'One New Orchard Road, Armonk, NY, United States, 10504',
//     FullTimeEmployees: '352600',
//     FiscalYearEnd: 'December',
//     LatestQuarter: '2020-12-31',
//     MarketCapitalization: '105425412096',
//     EBITDA: '13509000192',
//     PERatio: '18.9942',
//     PEGRatio: '8.8206',
//     BookValue: '23.075',
//     DividendPerShare: '6.52',
//     DividendYield: '0.055',
//     EPS: '6.229',
//     RevenuePerShareTTM: '82.691',
//     ProfitMargin: '0.0759',
//     OperatingMarginTTM: '0.0926',
//     ReturnOnAssetsTTM: '0.0276',
//     ReturnOnEquityTTM: '0.2638',
//     RevenueTTM: '73619996672',
//     GrossProfitTTM: '35575000000',
//     DilutedEPSTTM: '6.229',
//     QuarterlyEarningsGrowthYOY: '-0.632',
//     QuarterlyRevenueGrowthYOY: '-0.065',
//     AnalystTargetPrice: '138',
//     TrailingPE: '18.9942',
//     ForwardPE: '10.142',
//     PriceToSalesRatioTTM: '1.4445',
//     PriceToBookRatio: '5.1312',
//     EVToRevenue: '2.1508',
//     EVToEBITDA: '12.5472',
//     Beta: '1.2416',
//     '52WeekHigh': '150.8394',
//     '52WeekLow': '86.9458',
//     '50DayMovingAverage': '126.1122',
//     '200DayMovingAverage': '122.7232',
//     SharesOutstanding: '891057024',
//     SharesFloat: '891011172',
//     SharesShort: '24592416',
//     SharesShortPriorMonth: '22028993',
//     ShortRatio: '5.2',
//     ShortPercentOutstanding: '0.03',
//     ShortPercentFloat: '0.0276',
//     PercentInsiders: '0.128',
//     PercentInstitutions: '58.584',
//     ForwardAnnualDividendRate: '6.52',
//     ForwardAnnualDividendYield: '0.055',
//     PayoutRatio: '0.4865',
//     DividendDate: '2020-12-10',
//     ExDividendDate: '2020-11-09',
//     LastSplitFactor: '2:1',
//     LastSplitDate: '1999-05-27',
//   },
//   {
//     Symbol: 'AAPL',
//     AssetType: 'Common Stock',
//     Name: 'Apple Inc',
//     Description:
//       'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. It also sells various related services. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, HomePod, iPod touch, and other Apple-branded and third-party accessories. It also provides AppleCare support services; cloud services store services; and operates various platforms, including the App Store, that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts. In addition, the company offers various services, such as Apple Arcade, a game subscription service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV+, which offers exclusive original content; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It sells and delivers third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. was founded in 1977 and is headquartered in Cupertino, California.',
//     Exchange: 'NASDAQ',
//     Currency: 'USD',
//     Country: 'USA',
//     Sector: 'Technology',
//     Industry: 'Consumer Electronics',
//     Address: 'One Apple Park Way, Cupertino, CA, United States, 95014',
//     FullTimeEmployees: '147000',
//     FiscalYearEnd: 'September',
//     LatestQuarter: '2020-09-30',
//     MarketCapitalization: '2386553470976',
//     EBITDA: '77343997952',
//     PERatio: '43.25',
//     PEGRatio: '3.4629',
//     BookValue: '3.849',
//     DividendPerShare: '0.82',
//     DividendYield: '0.0059',
//     EPS: '3.28',
//     RevenuePerShareTTM: '15.82',
//     ProfitMargin: '0.2091',
//     OperatingMarginTTM: '0.2415',
//     ReturnOnAssetsTTM: '0.1251',
//     ReturnOnEquityTTM: '0.7369',
//     RevenueTTM: '274515001344',
//     GrossProfitTTM: '104956000000',
//     DilutedEPSTTM: '3.28',
//     QuarterlyEarningsGrowthYOY: '-0.023',
//     QuarterlyRevenueGrowthYOY: '0.01',
//     AnalystTargetPrice: '135.04',
//     TrailingPE: '43.25',
//     ForwardPE: '34.7222',
//     PriceToSalesRatioTTM: '8.8798',
//     PriceToBookRatio: '35.8073',
//     EVToRevenue: '8.601',
//     EVToEBITDA: '29.1422',
//     Beta: '1.2836',
//     '52WeekHigh': '145.08',
//     '52WeekLow': '52.8225',
//     '50DayMovingAverage': '129.3722',
//     '200DayMovingAverage': '117.1377',
//     SharesOutstanding: '16823300096',
//     SharesFloat: '16984460162',
//     SharesShort: '91091816',
//     SharesShortPriorMonth: '94721417',
//     ShortRatio: '0.84',
//     ShortPercentOutstanding: '0.01',
//     ShortPercentFloat: '0.0054',
//     PercentInsiders: '0.065',
//     PercentInstitutions: '59.662',
//     ForwardAnnualDividendRate: '0.82',
//     ForwardAnnualDividendYield: '0.0059',
//     PayoutRatio: '0.2469',
//     DividendDate: '2020-11-12',
//     ExDividendDate: '2020-11-06',
//     LastSplitFactor: '4:1',
//     LastSplitDate: '2020-08-31',
//   },
// ];
